# f = open("pradeep2.txt")
# print(f.tell())
# print(f.readline())
# print(f.tell())
# print(f.readline())
# print(f.tell())
# print(f.readlines())
f = open("pradeep2.txt")
print(f.tell())
f.seek(10)
print(f.readline())
f.close()